/*
 Navicat Premium Data Transfer

 Source Server         : local_scsb
 Source Server Type    : Oracle
 Source Server Version : 120200
 Source Host           : 192.168.56.103:1521
 Source Schema         : SCSB

 Target Server Type    : Oracle
 Target Server Version : 120200
 File Encoding         : 65001

 Date: 26/11/2021 08:39:31
*/


-- ----------------------------
-- Table structure for SCSB_MANAGER_ROLE_TASK
-- ----------------------------
DROP TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK";
CREATE TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" (
  "ROLE_ID" NVARCHAR2(50) VISIBLE NOT NULL,
  "TASK_ID" NVARCHAR2(20) VISIBLE NOT NULL,
  "CREATOR" NVARCHAR2(50) VISIBLE NOT NULL,
  "CREATE_TIME" DATE VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_ROLE_TASK"."ROLE_ID" IS '角色編號';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_ROLE_TASK"."TASK_ID" IS '功能編號';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_ROLE_TASK"."CREATOR" IS '建立者';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_ROLE_TASK"."CREATE_TIME" IS '建立時間';
COMMENT ON TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" IS '後台角色對應功能';

-- ----------------------------
-- Records of SCSB_MANAGER_ROLE_TASK
-- ----------------------------
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10013', 'Developer', TO_DATE('2021-11-10 05:52:14', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10014', 'Developer', TO_DATE('2021-11-10 05:52:29', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10019', 'Developer', TO_DATE('2021-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '100', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10001', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10002', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10003', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10004', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10005', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10006', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10007', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10008', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10009', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10010', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10011', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10012', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '200', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '300', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('1', '300', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('2', '200', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('2', '300', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '100', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '10001', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '10002', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '10003', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '10004', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '10005', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '10006', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '200', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('3', '300', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '100', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '10001', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '10002', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '10003', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '10004', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '10007', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '10008', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '200', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('4', '300', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '100', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '10001', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '10002', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '10003', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '10004', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '10009', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '10010', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '200', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('5', '300', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '100', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '10001', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '10002', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '10003', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '10004', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '10011', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '10012', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '200', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('6', '300', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('7', '100', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('7', '10001', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('7', '10002', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('7', '10003', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('7', '10004', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('7', '200', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('7', '300', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '20001', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '20002', 'Developer', TO_DATE('2021-04-15 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10015', 'Developer', TO_DATE('2021-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10016', 'Developer', TO_DATE('2021-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10017', 'Developer', TO_DATE('2021-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));
INSERT INTO "SCSB"."SCSB_MANAGER_ROLE_TASK" VALUES ('8', '10018', 'Developer', TO_DATE('2021-11-10 00:00:00', 'SYYYY-MM-DD HH24:MI:SS'));

-- ----------------------------
-- Primary Key structure for table SCSB_MANAGER_ROLE_TASK
-- ----------------------------
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007144" PRIMARY KEY ("ROLE_ID", "TASK_ID");

-- ----------------------------
-- Checks structure for table SCSB_MANAGER_ROLE_TASK
-- ----------------------------
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C0011764" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C0011765" CHECK ("TASK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C0011766" CHECK ("CREATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007138" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007139" CHECK ("TASK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007140" CHECK ("CREATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007141" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007142" CHECK ("TASK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007143" CHECK ("CREATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007317" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007318" CHECK ("TASK_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_ROLE_TASK" ADD CONSTRAINT "SYS_C007319" CHECK ("CREATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
/*
 Navicat Premium Data Transfer

 Source Server         : local_scsb
 Source Server Type    : Oracle
 Source Server Version : 120200
 Source Host           : 192.168.56.103:1521
 Source Schema         : SCSB

 Target Server Type    : Oracle
 Target Server Version : 120200
 File Encoding         : 65001

 Date: 26/11/2021 08:40:21
*/


-- ----------------------------
-- Table structure for SCSB_MANAGER_TASK
-- ----------------------------
DROP TABLE "SCSB"."SCSB_MANAGER_TASK";
CREATE TABLE "SCSB"."SCSB_MANAGER_TASK" (
  "ID" NVARCHAR2(50) VISIBLE NOT NULL,
  "NAME" NVARCHAR2(200) VISIBLE,
  "URL" NVARCHAR2(225) VISIBLE,
  "PARENT_ID" NVARCHAR2(50) VISIBLE,
  "CATEGORY" NVARCHAR2(10) VISIBLE,
  "SORT" NUMBER(11,0) VISIBLE,
  "STATUS" NCHAR(1) VISIBLE NOT NULL,
  "IMAGES" NVARCHAR2(50) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_TASK"."ID" IS '編號';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_TASK"."NAME" IS '名稱';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_TASK"."URL" IS '功能連結';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_TASK"."PARENT_ID" IS '父功能編號';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_TASK"."CATEGORY" IS '左側選單頁面下的分類';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_TASK"."SORT" IS '排序';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_TASK"."STATUS" IS '狀態 1:開啟 0:關閉';
COMMENT ON COLUMN "SCSB"."SCSB_MANAGER_TASK"."IMAGES" IS '圖片';
COMMENT ON TABLE "SCSB"."SCSB_MANAGER_TASK" IS '後台功能';

-- ----------------------------
-- Records of SCSB_MANAGER_TASK
-- ----------------------------
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10013', '廣告輪播', '/card/banner/add', '100', '信用卡', '13', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10014', '廣告', '/card/ad/add', '100', '信用卡', '14', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10015', '熱門活動', '/card/swipeDiscount/hot/add', '100', '信用卡>刷卡優惠', '15', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10016', '新戶禮', '/card/swipeDiscount/gift/add', '100', '信用卡>刷卡優惠', '16', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10017', '優惠商店', '/card/swipeDiscount/discountShop/add', '100', '信用卡>刷卡優惠', '17', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10018', '紅利兌換', '/card/reward/add', '100', '信用卡>紅利積點', '18', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10019', '刷卡優惠', '/card/debit/add', '100', '信用卡>Debit卡', '19', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('100', '頁面', '#', NULL, '提交表單', '1', '1', 'fas fa-folder');
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10001', '本行公告', '/indexAnnounce/add', '100', '首頁', '1', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10002', '最新活動', '/indexActivity/add', '100', '首頁', '2', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10003', '廣告輪播', '/indexBanner/add', '100', '首頁', '3', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10004', '中獎名單', '/indexWinners/add', '100', '首頁', '4', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10005', '廣告輪播', '/businessBanner/add', '100', '企業金融', '5', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10006', '廣告', '/businessAd/add', '100', '企業金融', '6', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10007', '廣告輪播', '/personalBanner/add', '100', '個人金融', '7', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10008', '廣告', '/personalAd/add', '100', '個人金融', '8', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10009', '廣告輪播', '/depositBanner/add', '100', '台外幣存匯', '9', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10010', '廣告', '/depositAd/add', '100', '台外幣存匯', '10', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10011', '廣告輪播', '/digitBanner/add', '100', '數位金融', '11', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('10012', '廣告', '/digitAd/add', '100', '數位金融', '12', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('200', '待核表單', '#', NULL, '表單管理', '2', '1', 'fas fa-clipboard-check');
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('300', '表單查詢/停刊', '/recordSheet/list', NULL, '表單管理', '3', '1', 'fas fa-clipboard-list');
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('20002', '停刊', '/cancelSheet/list', '200', '待核表單', '2', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('20001', '刊登', '/pendingSheet/list', '200', '待核表單', '1', '1', NULL);
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('500', '系統提醒', '/remindEmailSetting/edit', NULL, '後台設定', '5', '1', 'fas fa-stopwatch');
INSERT INTO "SCSB"."SCSB_MANAGER_TASK" VALUES ('400', '管理者表單', '/recordAllSheet/list', NULL, '後台設定', '4', '1', 'fas fa-users-cog');

-- ----------------------------
-- Primary Key structure for table SCSB_MANAGER_TASK
-- ----------------------------
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C007121" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table SCSB_MANAGER_TASK
-- ----------------------------
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C0011777" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C0011778" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C007117" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C007118" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C007119" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C007120" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C007320" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_MANAGER_TASK" ADD CONSTRAINT "SYS_C007321" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
/*
 Navicat Premium Data Transfer

 Source Server         : local_scsb
 Source Server Type    : Oracle
 Source Server Version : 120200
 Source Host           : 192.168.56.103:1521
 Source Schema         : SCSB

 Target Server Type    : Oracle
 Target Server Version : 120200
 File Encoding         : 65001

 Date: 26/11/2021 08:40:39
*/


-- ----------------------------
-- Table structure for SCSB_SHEET
-- ----------------------------
DROP TABLE "SCSB"."SCSB_SHEET";
CREATE TABLE "SCSB"."SCSB_SHEET" (
  "ID" NUMBER(11,0) VISIBLE NOT NULL,
  "TYPE" NVARCHAR2(11) VISIBLE NOT NULL,
  "APPLICANT_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "APPLICANT" NVARCHAR2(255) VISIBLE NOT NULL,
  "ON_TIME" DATE VISIBLE NOT NULL,
  "OFF_TIME" DATE VISIBLE NOT NULL,
  "NEXT_APPROVER_ID" NVARCHAR2(255) VISIBLE NOT NULL,
  "NEXT_APPROVER" NVARCHAR2(255) VISIBLE NOT NULL,
  "AGENT_ID" NVARCHAR2(255) VISIBLE,
  "AGENT" NVARCHAR2(255) VISIBLE,
  "CATEGORY" NVARCHAR2(20) VISIBLE,
  "TITLE" NVARCHAR2(40) VISIBLE,
  "IMAGE" NVARCHAR2(300) VISIBLE,
  "IMAGE_URL" NVARCHAR2(300) VISIBLE,
  "FILE" NVARCHAR2(300) VISIBLE,
  "FILE2" NVARCHAR2(300) VISIBLE,
  "FILE3" NVARCHAR2(300) VISIBLE,
  "FILE4" NVARCHAR2(300) VISIBLE,
  "FILE5" NVARCHAR2(300) VISIBLE,
  "CONTENT" NCLOB VISIBLE,
  "ARCHIVE_REASON" NVARCHAR2(100) VISIBLE,
  "STEP" NUMBER(11,0) VISIBLE NOT NULL,
  "STATUS" NCHAR(1) VISIBLE NOT NULL,
  "CREATOR" NVARCHAR2(255) VISIBLE NOT NULL,
  "CREATE_TIME" TIMESTAMP(6) VISIBLE DEFAULT SYSTIMESTAMP NOT NULL,
  "MODIFIER" NVARCHAR2(255) VISIBLE NOT NULL,
  "MODIFY_TIME" TIMESTAMP(6) VISIBLE DEFAULT SYSTIMESTAMP NOT NULL,
  "APPLICANT_UNIT" NVARCHAR2(255) VISIBLE,
  "APPLICANT_UNIT_ID" NVARCHAR2(255) VISIBLE,
  "IMAGE_MOBILE" NVARCHAR2(300) VISIBLE
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."ID" IS '編號';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."TYPE" IS '表單型態 0:本行公告,1:最新活動,2:廣告輪播,3:中獎名單,4:企金輪播,5:企金廣告,6:個金輪播,7:個金廣告,8:台外幣輪播,9:台外幣廣告,10:數金輪播,11:數金廣告';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."APPLICANT_ID" IS '申請人編號';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."APPLICANT" IS '申請人姓名';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."ON_TIME" IS '刊登時間';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."OFF_TIME" IS '停刊時間';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."NEXT_APPROVER_ID" IS '審核人編號';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."NEXT_APPROVER" IS '審核人姓名';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."AGENT_ID" IS '代理人編號';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."AGENT" IS '代理人姓名';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."CATEGORY" IS '表單分類';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."TITLE" IS '標題';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."IMAGE" IS '電腦版圖檔位置';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."IMAGE_URL" IS '圖檔連結';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."FILE" IS '檔案位置';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."FILE2" IS '檔案位置2';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."FILE3" IS '檔案位置3';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."FILE4" IS '檔案位置4';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."FILE5" IS '檔案位置5';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."CONTENT" IS '內容';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."ARCHIVE_REASON" IS '下架原因';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."STEP" IS '審核階段';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."STATUS" IS '狀態 0:處理中-刊登,1:已通過,2:已退回,3:已下架,4:處理中-停刊';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."CREATOR" IS '建立者';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."CREATE_TIME" IS '建立時間';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."MODIFIER" IS '修改者';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."MODIFY_TIME" IS '修改時間';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."APPLICANT_UNIT" IS '申請單位名稱';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."APPLICANT_UNIT_ID" IS '申請單位編號';
COMMENT ON COLUMN "SCSB"."SCSB_SHEET"."IMAGE_MOBILE" IS '手機版圖檔位置';

-- ----------------------------
-- Checks structure for table SCSB_SHEET
-- ----------------------------
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011870" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011871" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011872" CHECK ("APPLICANT_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011873" CHECK ("APPLICANT" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011874" CHECK ("ON_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011875" CHECK ("OFF_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011876" CHECK ("NEXT_APPROVER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011877" CHECK ("NEXT_APPROVER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011878" CHECK ("STEP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011879" CHECK ("STATUS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011880" CHECK ("CREATOR" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011881" CHECK ("CREATE_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011882" CHECK ("MODIFIER" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCSB"."SCSB_SHEET" ADD CONSTRAINT "SYS_C0011883" CHECK ("MODIFY_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Indexes structure for table SCSB_SHEET
-- ----------------------------
CREATE INDEX "SCSB"."SCSB_SHEET_MUTI_IX1"
  ON "SCSB"."SCSB_SHEET" ("TYPE" ASC, "STATUS" ASC)
  LOGGING
  VISIBLE
PCTFREE 10
INITRANS 2
STORAGE (
  INITIAL 16384 
  NEXT 16384 
  MINEXTENTS 1
  MAXEXTENTS 505
  PCTINCREASE 50
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
  FLASH_CACHE DEFAULT
)
   USABLE;
